services:
  db:
    image: postgres:15
    container_name: kiosco_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: kiosco_db
    ports:
      - "5433:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  backend:
    build: ./Backend
    container_name: kiosco_backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: secretpassword
      DB_NAME: kiosco_db
      DB_PORT: 5432
    depends_on:
      - db

  frontend:
    build: ./Frontend
    ports:
      - "8080:80"
    depends_on:
      - backend