FROM node:24-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install --omit=dev

COPY . .

EXPOSE 3000

##CMD ["node_modules/.bin/nodemon", "src/index.js"]

CMD ["node", "src/index.js"]  
#version produccion